export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const FETCH_TOP_ARTISTS_LONG_TERM = 'FETCH_TOP_ARTISTS_LONG_TERM';
export const FETCH_TOP_ARTISTS_MEDIUM_TERM = 'FETCH_TOP_ARTISTS_MEDIUM_TERM';
export const FETCH_TOP_ARTISTS_SHORT_TERM = 'FETCH_TOP_ARTISTS_SHORT_TERM';

export const FETCH_TOP_SONGS_LONG_TERM = 'FETCH_TOP_SONGS_LONG_TERM';
export const FETCH_TOP_SONGS_MEDIUM_TERM = 'FETCH_TOP_SONGS_MEDIUM_TERM';
export const FETCH_TOP_SONGS_SHORT_TERM = 'FETCH_TOP_SONGS_SHORT_TERM';

export const FETCH_RECENTLY_PLAYED = 'FETCH_RECENTLY_PLAYED';

export const FETCH_AUDIO_FEATURES = 'FETCH_AUDIO_FEATURES';
